[package]
name = "ynabber"
version = "0.1.0"
authors = ["Rich Churcher <rich.churcher@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
serde_with = "1.3.1"
rusty-money = "0.4.1"
